### PR TITLE
Allow CORS

### PR DESCRIPTION
**Pull request by monsterkrampe**
#### Why did I do this?

I wanted to use fakeit locally to mock an API which is not written yet.
The Problem I had was, that my frontend running on `localhost:3000` could not access `localhost:8080` due to the browser forbidding cross origin requests.

For this reason I thought, that it would be useful to have an option that adds a wildcard `Access-Control-Allow-Origin` Header to all Responses.

Please let me know if you would have done something differently. I'm not experienced with `Rack`, so there might be a better place to inject the additional header.

### CODE REVIEW

**Comment by JustinFeng** [comment]
Hi @monsterkrampe, thank you for your PR, this is a good catch, CORS is definitely a important feature to enable web development against fakeit. Some suggestion about the PR:

* Probably no need to control it by options, security is not a concern for such mock server, I reckon it is much convenient to always enable CORS for now
* I would prefer to leverage existing rack based CORS solution, like https://github.com/cyu/rack-cors middleware

Please feel free to update your PR, or I can implement it during the weekend along with some other features.Thanks again for your feedback

**Comment by monsterkrampe** [comment]
Hey @JustinFeng,thanks for your advice.
I honestly don't know why I did not search for something like rack-cors yet.
I'm definitely going to use this.

**Comment by monsterkrampe** [comment]
This should do it.
Again, let me know what you think :)

**Comment by JustinFeng** [comment]
LGTM, thank you for contribution

**Comment by JustinFeng** [comment]
BTW, I'm planning to release this weekend or early next week

**Pull request merged**
